repos:
- hooks:
  - id: black
    exclude: '^env/'
    exclude: '^dvc/'
    files: '.*\.py'
    language_version: python3
  repo: https://github.com/ambv/black
  rev: 21.9b0
-   repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    -   id: seed-isort-config
- hooks:
  - id: isort
    language_version: python3
  repo: https://github.com/timothycrosley/isort
  rev: 5.9.3
- hooks:
  - id: flake8
    exclude: '^env/'
    exclude: '^dvc/'
    files: '.*\.py'
    language_version: python3
  repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
