name: DVC benchmarks
on: [push, pull_request]

jobs:
  verify:
    name: tests and styling check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - uses: actions/setup-python@v2
        with:
            python-version: 3.7
      - uses: actions/checkout@v2
      - name: install requirements
        run: pip install -r requirements.txt
      - name: check project styling
        if: matrix.os == 'ubuntu-latest'
        run: pre-commit run --all-files
      - name: run tests
        run: python -m py.test
  build:
    name: benchmarks
    needs: verify
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - uses: actions/setup-python@v2
        with:
            python-version: 3.7
      - uses: actions/checkout@v2
      - name: install requirements
        run: pip install -r requirements.txt
      - name: setup asv machine
        run: python write_asv_machine.py
      - name: run benchmarks
        run: dvc repro run_benchmarks.dvc
      - name: convert results to static website
        run: asv publish
      - name: upload html
        uses: actions/upload-artifact@v2
        with:
          name: html-${{ matrix.os }}
          path: html
      - name: upload raw results
        uses: actions/upload-artifact@v2
        with:
          name: results-${{ matrix.os }}
          path: results
      - name: deploy new benchmarks to github pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/master' && matrix.os == 'ubuntu-latest'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: html
